apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/VuxLuan/nd064_course_1/tree/main/project
    path: helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-staging.yaml
