apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VuxLuan/nd064_course_1
    targetRevision: HEAD
    path: project/helm
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
